admin: 
  setcoins: admin/setcoins.ejs
  userinfo: admin/userinfo.ejs
  coupon: admin/coupon.ejs
  package: admin/package.ejs
  
pages:
  login: login.ejs
  home: home.ejs
  store: store.ejs
  server/create: create.ejs
  earn: earn.ejs
  lv: lv.ejs
  j4r: j4r.ejs

redirects: 
  callback: /home
  invalid_amount: /store?error=Invalid_Amount
  cant_afford: /store?error=Cant_Afford
  store_error: /store?error=An_Error_Occured
  store_sucess: /store?sucess=true
